#!/bin/bash

node dist/index --nameSpace field-pros --bgWindow none --bgMain Green_BG_01.svg --bgAlt Grid_Graphic-01.svg --bgMondrian Grid_Graphic-01.svg --brandLogo Logo_ColorBars-01.svg --primaryColor '5B5B5B' --secondaryColor 'FFFFFF' --accentColor '6BAA36' --highlightColor '107,170,54' --headerFont 'Roboto Condensed, sans-serif, 700' --bodyFont 'Lato, sans-serif, 300' --accentFont 'Lato, sans-serif, 300' --linkColor '6BAA36'
node dist/index --nameSpace narrasys --bgWindow Narrasys_Tree.svg --bgMain none --bgAlt none --bgMondrian none --brandLogo Narrasys_brand_logo.svg --primaryColor '4D4D4D' --secondaryColor 'FFFFFF' --accentColor 'DE6625' --highlightColor '222,102,37' --headerFont 'Gotham Medium, sans-serif' --bodyFont 'Gotham Thin, sans-serif' --accentFont 'Gotham Light Italic, sans-serif' --linkColor 'DE6626'
node dist/index --nameSpace career-playbook --bgWindow CPB_Window_BG_720.png --bgMain CPB_ModernSqaures-01.svg --bgAlt CPB_Textured_BG_v3.png --bgMondrian none --brandLogo CPB_Logo-01-2.svg --primaryColor '4D4D4D' --secondaryColor 'FFFFFF' --accentColor '00ACEE' --highlightColor '0,172,238' --headerFont 'Lato, sans-serif, 700' --bodyFont 'Lato, sans-serif, 300' --accentFont 'Lato, sans-serif, 300, italic' --linkColor '00ACEE'
node dist/index --nameSpace unbranded --bgWindow none --bgMain none --bgAlt none --bgMondrian none --brandLogo Narrasys_Banner_white.svg --primaryColor '000000' --secondaryColor 'DDDDDD' --accentColor 'CCCCCC' --highlightColor '204,204,204' --headerFont 'Open Sans, sans-serif, 700' --bodyFont 'Open Sans, sans-serif, 400' --accentFont 'Droid Serif, serif, 400' --linkColor '0000CC'
node dist/index --nameSpace george-washington --bgWindow none --bgMain none --bgAlt none --bgMondrian none --brandLogo none --primaryColor '000000' --secondaryColor 'FFFFFF' --accentColor '004065' --highlightColor '200,177,139' --headerFont 'Helvetica, sans-serif, 700' --bodyFont 'Helvetica, sans-serif, 300' --accentFont 'Cardo, serif, 300' --linkColor '004065';
node dist/index --nameSpace university-arizona --bgWindow UofA_Fullscreen_BG_Square.png --bgMain none --bgAlt none --bgMondrian none --brandLogo ua_horiz.svg --primaryColor '072D5B' --secondaryColor 'FFFFFF' --accentColor 'AB0520' --highlightColor '171,5,32' --headerFont 'Noto Sans, sans-serif, 700' --bodyFont 'Noto Sans, sans-serif, 400' --accentFont 'Amiri, serif, 300' --linkColor 'AB0520'
node dist/index --nameSpace chef-ann-foundation --bgWindow CAF_Player_Background.svg --bgMain none --bgAlt none --bgMondrian none --brandLogo School_Food_Academy_Logo_Final.svg --primaryColor '3c3529' --secondaryColor 'FFFFFF' --accentColor '662e6b' --highlightColor '102,46,107' --headerFont 'Muli, sans-serif, 600' --bodyFont 'Muli, sans-serif, 400' --accentFont 'Muli, sans-serif, 300, italic' --linkColor '662e6b'
